# Generated by Django 3.0.8 on 2020-08-31 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registrationno', models.CharField(max_length=10)),
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('parentcontactno', models.IntegerField()),
                ('DOA', models.DateField()),
                ('DOB', models.DateField()),
                ('classname', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=150)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contactno', models.IntegerField()),
                ('DOJ', models.DateField()),
                ('DOB', models.DateField()),
                ('qualification', models.TextField(max_length=1000)),
                ('department', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('basicpay', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case2.Topic')),
            ],
            options={
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationno', models.CharField(max_length=10)),
                ('subjectname', models.CharField(max_length=200)),
                ('marksobtained', models.IntegerField()),
                ('passmarks', models.IntegerField()),
                ('maximummarks', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Results',
            },
        ),
    ]
